name: main
on:
  pull_request:
    branches:
      - main
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: dependency review
        uses: actions/dependency-review-action@v4
      - name: audit
        run: npm audit --audit-level=high --omit=dev
      - name: install packages
        run: npm ci
      - name: format
        run: npm run format
      - name: run check
        run: npm run check
      - name: cypress
        uses: cypress-io/github-action@v6
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_SERVICE_API_KEY: ${{ secrets.MICROCMS_SERVICE_API_KEY }}
          MICROCMS_TOPPAGE_ID: ${{ secrets.MICROCMS_TOPPAGE_ID }}
        with:
          browser: chrome
          start: npm run dev
          command: npx cypress run
          wait-on: 'http://localhost:4321/'
